/**
 * ManageSpace Lease API
 * ManageSpace Lease API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CalculateProratedAmountResponse { 
    /**
     * A positive number representing amount due or a negative amount representing credit.
     */
    amount: number;
    /**
     * Payment provider description for charges.
     */
    description: string;
    /**
     * Payment provider description for charges.
     */
    detailedDescription: string;
    /**
     * Representing the beginning of the period for which the proration is being calculated.
     */
    prorationStartDate: string;
    /**
     * Representing the end of the period for which the proration is being calculated.
     */
    prorationEndDate: string;
    /**
     * Date representing the end of the current billing period.
     */
    originalBillingCycleAnchor: string;
    /**
     * Date representing the end of the current billing period.
     */
    paidThrough: string;
    /**
     * Adjusted date used for proration calculation.
     */
    adjustedFutureDate: string;
    /**
     * Amount in centes representing the price associated with the current subscription plan.
     */
    subscriptionAmount: number;
    /**
     * Payment provider customer id
     */
    customerId: string;
    /**
     * Payment provider subscription id
     */
    subscriptionId: string;
    /**
     * A positive number representing amount due or a negative amount representing credit.
     */
    daysBetween: number;
}

