/**
 * ManageSpace Lease API
 * ManageSpace Lease API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MoveOutV2Response } from './moveOutV2Response';


export interface CreateMoveOutV2200Response { 
    data?: Array<MoveOutV2Response>;
    success?: boolean;
    error?: object;
}

