/**
 * ManageSpace Lease API
 * ManageSpace Lease API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SpaceReservationFeatureRequest } from './spaceReservationFeatureRequest';


export interface CreateSpaceReservationRequest { 
    /**
     * Space Reservation Notes
     */
    notes: string | null;
    /**
     * Expires At
     */
    expiresAt?: string | null;
    /**
     * Minimum Price
     */
    minPrice: number;
    /**
     * Maximum Price
     */
    maxPrice: number;
    /**
     * Length of Unit
     */
    length: number;
    /**
     * Width of Unit
     */
    width: number;
    /**
     * Height of Unit
     */
    height?: number | null;
    /**
     * Features for the Unit
     */
    features: Array<SpaceReservationFeatureRequest>;
}

