/**
 * ManageSpace Lease API
 * ManageSpace Lease API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateReservationRequest { 
    /**
     * Account ID
     */
    accountId: string;
    /**
     * Reservation Notes
     */
    notes: string | null;
    /**
     * Expires At
     */
    expiresAt?: string | null;
}

