/**
 * ManageSpace Lease API
 * ManageSpace Lease API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LeaseResponse } from './leaseResponse';


export interface GetLease200Response { 
    data?: Array<LeaseResponse>;
    success?: boolean;
    error?: object;
}

