/**
 * ManageSpace Lease API
 * ManageSpace Lease API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RentalResponse } from './rentalResponse';


export interface GetRental200Response { 
    data?: Array<RentalResponse>;
    success?: boolean;
    error?: object;
}

