/**
 * ManageSpace Lease API
 * ManageSpace Lease API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RentalType } from './rentalType';
import { SubscriptionProductResponse } from './subscriptionProductResponse';
import { RentalStatus } from './rentalStatus';


export interface RentalResponse { 
    /**
     * Rental ID
     */
    rentalId: string;
    /**
     * Unit ID
     */
    unitId: string;
    /**
     * Unit Name
     */
    unitName: string;
    /**
     * Site ID
     */
    siteId: string;
    /**
     * Org ID
     */
    orgId: string;
    /**
     * Account ID of the lessee
     */
    accountId: string;
    /**
     * Account Name
     */
    accountName: string;
    /**
     * Account Email Address
     */
    email: string | null;
    /**
     * Account Mobile Number
     */
    mobileNumber: string;
    rentalType: RentalType;
    /**
     * Reservation ID
     */
    reservationId: string | null;
    /**
     * Notes.
     */
    notes: string | null;
    /**
     * Access code.
     */
    accessCode: string;
    /**
     * Intended move out date.
     */
    intendedMoveOutDate: string | null;
    /**
     * Move out date.
     */
    moveOutDate: string | null;
    /**
     * Expiration date.
     */
    expiresAt: string | null;
    /**
     * Effective date.
     */
    effectiveDate: string;
    /**
     * Amount of the subscription
     */
    amount: number;
    /**
     * Rental start date
     */
    startDate: string;
    /**
     * Rental fee percent
     */
    feePercent: number;
    rentalStatus: RentalStatus;
    /**
     * Created at.
     */
    createdAt: string;
    /**
     * Sub products on the rental
     */
    subscriptionProducts: Array<SubscriptionProductResponse>;
}
export namespace RentalResponse {
}


