/**
 * ManageSpace Lease API
 * ManageSpace Lease API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type RentalType = 'fixed_term' | 'month_to_month';

export const RentalType = {
    FixedTerm: 'fixed_term' as RentalType,
    MonthToMonth: 'month_to_month' as RentalType
};

