/**
 * ManageSpace Lease API
 * ManageSpace Lease API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RentalAgreementResponse { 
    /**
     * Rental agreement ID
     */
    rentalAgreementId: string;
    /**
     * Account ID
     */
    accountId: string;
    /**
     * Account full name.
     */
    accountName: string;
    /**
     * Document ID
     */
    documentId: string;
    /**
     * Org ID
     */
    orgId: string;
    /**
     * Created by
     */
    createdBy: string;
    /**
     * Updated by
     */
    updatedBy: string | null;
    /**
     * Created at.
     */
    createdAt: string;
    /**
     * Updated at.
     */
    updatedAt?: string | null;
}

