/**
 * ManageSpace Lease API
 * ManageSpace Lease API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReservationStatus } from './reservationStatus';


export interface ReservationResponse { 
    /**
     * Reservation ID
     */
    reservationId: string;
    /**
     * Unit ID
     */
    unitId: string;
    /**
     * Unit Name
     */
    unitName: string;
    /**
     * Site ID
     */
    siteId: string;
    /**
     * Organization ID
     */
    orgId: string;
    /**
     * Account ID
     */
    accountId: string;
    /**
     * Account Name
     */
    accountName: string;
    /**
     * Account Email Address
     */
    email: string | null;
    /**
     * Account Mobile Number
     */
    mobileNumber: string;
    /**
     * Reservation Notes
     */
    notes?: string | null;
    /**
     * Expires At
     */
    expiresAt: string;
    /**
     * Created date
     */
    createdAt: string | null;
    status: ReservationStatus;
}

