/**
 * ManageSpace Lease API
 * ManageSpace Lease API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountStatsSpaceReservation } from './accountStatsSpaceReservation';


export interface SpaceReservationGroupedResponse { 
    /**
     * Grouped by facet, ex: `10x10`
     */
    groupedByFacet: string;
    /**
     * The count of reserved unit spaces.
     */
    reservedCount: number;
    /**
     * List of accounts
     */
    accounts: Array<AccountStatsSpaceReservation>;
}

