/**
 * ManageSpace Lease API
 * ManageSpace Lease API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SubscriptionProductResponse { 
    /**
     * Subscription productId ID
     */
    subscriptionProductId: string;
    /**
     * Product ID
     */
    productId: string;
    /**
     * Account ID
     */
    accountId: string;
    /**
     * Site ID
     */
    siteId: string;
    /**
     * Org ID
     */
    orgId: string;
    /**
     * Amount of the subscription product
     */
    amount: number;
    /**
     * Start date.
     */
    startDate: string | null;
    /**
     * end date.
     */
    endDate: string | null;
    /**
     * Rental ID
     */
    rentalId: string;
}

